/*
 * Automatically generated by Magic.
 */
CREATE TABLE checkout_sessions(
  session_id varchar(25) not null primary key,
  username text not null,
  price text not null,
  created timestamp not null default current_timestamp
);
